import { useState } from "react";
import {
  Button,
  Card,
  ProgressBar,
  Radio,
  RadioGroup,
  Spinner,
  Text,
  makeStyles,
  shorthands,
  tokens,
  Input,
  Combobox,
  Option,
  Badge,
} from "@fluentui/react-components";
import {
  Timer20Regular,
  Trophy20Regular,
  ArrowRight20Regular,
} from "@fluentui/react-icons";
import { api } from "../../api/http";

const useStyles = makeStyles({
  root: {
    maxWidth: "800px",
    margin: "0 auto",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  card: {
    ...shorthands.padding("24px"),
    borderRadius: "16px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.05)",
  },
  header: {
    textAlign: "center",
    marginBottom: "20px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    color: tokens.colorNeutralForeground1,
  },
  subtitle: {
    color: tokens.colorNeutralForeground2,
    marginTop: "8px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    maxWidth: "400px",
    margin: "0 auto",
    width: "100%",
  },
  questionContainer: {
    marginTop: "20px",
  },
  questionText: {
    fontSize: "18px",
    fontWeight: 600,
    marginBottom: "16px",
    display: "block",
  },
  options: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  navigation: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "24px",
  },
  resultContainer: {
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    padding: "40px 0",
  },
  scoreBadge: {
    fontSize: "48px",
    fontWeight: "bold",
    color: tokens.colorBrandForeground1,
  },
});

type Question = {
  id: number;
  question: string;
  options: string[];
  correctAnswer: string;
};

export default function CandidateSkillTest() {
  const styles = useStyles();
  const [step, setStep] = useState<"setup" | "loading" | "test" | "result">("setup");
  const [skill, setSkill] = useState("");
  const [level, setLevel] = useState("Intermediate");
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [score, setScore] = useState(0);
  const [error, setError] = useState("");

  const startTest = async () => {
    if (!skill.trim()) {
      setError("Please enter a skill.");
      return;
    }
    setError("");
    setStep("loading");
    try {
      const res = await api<{ questions: Question[] }>("/api/skill-tests/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ skill, level }),
      });
      
      if (res.questions && res.questions.length > 0) {
        setQuestions(res.questions);
        setStep("test");
        setCurrentQuestionIndex(0);
        setAnswers({});
      } else {
        throw new Error("No questions generated.");
      }
    } catch {
      setError("Failed to generate test. Please try again.");
      setStep("setup");
    }
  };

  const handleAnswer = (val: string) => {
    setAnswers((prev) => ({ ...prev, [currentQuestionIndex]: val }));
  };

  const nextQuestion = () => {
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex((p) => p + 1);
    } else {
      submitTest();
    }
  };

  const submitTest = () => {
    let correctCount = 0;
    questions.forEach((q, idx) => {
      if (answers[idx] === q.correctAnswer) {
        correctCount++;
      }
    });
    setScore(correctCount);
    setStep("result");
  };

  const reset = () => {
    setStep("setup");
    setSkill("");
    setQuestions([]);
    setAnswers({});
    setScore(0);
  };

  return (
    <div className={styles.root}>
      <Card className={styles.card}>
        {step === "setup" && (
          <div className={styles.header}>
            <Text className={styles.title}>AI Skill Assessment</Text>
            <Text className={styles.subtitle} block>
              Test your knowledge on any topic. Questions are generated by AI.
            </Text>

            <div className={styles.form} style={{ marginTop: "30px" }}>
              {error && <Text style={{ color: tokens.colorPaletteRedForeground1 }}>{error}</Text>}
              
              <div>
                <Text weight="semibold">Skill / Topic</Text>
                <Input 
                  value={skill} 
                  onChange={(_, d) => setSkill(d.value)} 
                  placeholder="e.g. React, Python, Project Management" 
                  style={{ width: "100%", marginTop: "4px" }}
                />
              </div>

              <div>
                <Text weight="semibold">Difficulty Level</Text>
                <Combobox
                  value={level}
                  onOptionSelect={(_, d) => setLevel(d.optionValue || "Intermediate")}
                  style={{ width: "100%", marginTop: "4px" }}
                >
                  <Option>Beginner</Option>
                  <Option>Intermediate</Option>
                  <Option>Advanced</Option>
                </Combobox>
              </div>

              <Button appearance="primary" size="large" onClick={() => void startTest()}>
                Start Test
              </Button>
            </div>
          </div>
        )}

        {step === "loading" && (
           <div className={styles.resultContainer}>
             <Spinner size="large" label="Generating questions..." />
             <Text>This usually takes 5-10 seconds.</Text>
           </div>
        )}

        {step === "test" && questions.length > 0 && (
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "10px" }}>
              <Badge appearance="tint" color="brand">{skill} • {level}</Badge>
              <Text><Timer20Regular /> Unlimited Time</Text>
            </div>
            
            <ProgressBar value={currentQuestionIndex + 1} max={questions.length} />
            <Text size={200} style={{ marginTop: "4px", display: "block", textAlign:"right" }}>
              Question {currentQuestionIndex + 1} of {questions.length}
            </Text>

            <div className={styles.questionContainer}>
              <Text className={styles.questionText}>
                {questions[currentQuestionIndex].question}
              </Text>
              
              <RadioGroup 
                value={answers[currentQuestionIndex] || ""} 
                onChange={(_, d) => handleAnswer(d.value)}
                className={styles.options}
              >
                {questions[currentQuestionIndex].options.map((opt, idx) => (
                  <Radio key={idx} value={opt} label={opt} />
                ))}
              </RadioGroup>
            </div>

            <div className={styles.navigation}>
               <Button 
                 disabled={currentQuestionIndex === 0} 
                 onClick={() => setCurrentQuestionIndex(p => p - 1)}
               >
                 Previous
               </Button>
               <Button 
                 appearance="primary" 
                 onClick={nextQuestion}
                 icon={<ArrowRight20Regular />}
                 iconPosition="after"
                 disabled={!answers[currentQuestionIndex]}
               >
                 {currentQuestionIndex === questions.length - 1 ? "Finish" : "Next"}
               </Button>
            </div>
          </div>
        )}

        {step === "result" && (
          <div className={styles.resultContainer}>
            <Trophy20Regular style={{ fontSize: "64px", color: "#FFD700" }} />
            <Text className={styles.title}>Test Completed!</Text>
            
            <div>
              <Text size={500}>You scored</Text>
              <div className={styles.scoreBadge}>
                {score} / {questions.length}
              </div>
            </div>

            <div style={{ display: "flex", gap: "10px", marginTop: "20px" }}>
               <Button appearance="outline" onClick={reset}>Take Another Test</Button>
               <Button appearance="primary" onClick={() => window.history.back()}>Back to Dashboard</Button>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}
